#!/bin/bash

if [ $# -eq 0 ]; then
  error_print "No arguments supplied"
  exit 1
fi

if [[ ! -d "${1}" ]]; then
  error_print "Root must be directory"
  exit 1
fi

FULL_PATH=${1}/${2}

if [[ -d "${FULL_PATH}" ]]; then
  pushd ${FULL_PATH}
  exit 0
fi

if [[ -f "${FULL_PATH}" ]]; then
  warning_print "Target is file, changing to its directory"
  pushd $(dirname ${FULL_PATH})
  exit 0
fi

warning_print "Target could not be found, changing to Root directory"
pushd ${1}